/* tslint:disable */
/* eslint-disable */
/**
 * Blood Donors Api
 * Blood donor registration and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xvancoa@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DonationType,
} from '../models';
import {
    DonationTypeFromJSON,
    DonationTypeToJSON,
} from '../models';

export interface GetDonationTypesRequest {
    siteId: string;
}

/**
 * DonationTypesApi - interface
 * 
 * @export
 * @interface DonationTypesApiInterface
 */
export interface DonationTypesApiInterface {
    /**
     * By using siteId you get list of predefined donation types
     * @summary Provides the list of donation types associated with the donation site
     * @param {string} siteId pass the id of the particular donation site
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonationTypesApiInterface
     */
    getDonationTypesRaw(requestParameters: GetDonationTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DonationType>>>;

    /**
     * By using siteId you get list of predefined donation types
     * Provides the list of donation types associated with the donation site
     */
    getDonationTypes(requestParameters: GetDonationTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DonationType>>;

}

/**
 * 
 */
export class DonationTypesApi extends runtime.BaseAPI implements DonationTypesApiInterface {

    /**
     * By using siteId you get list of predefined donation types
     * Provides the list of donation types associated with the donation site
     */
    async getDonationTypesRaw(requestParameters: GetDonationTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DonationType>>> {
        if (requestParameters.siteId === null || requestParameters.siteId === undefined) {
            throw new runtime.RequiredError('siteId','Required parameter requestParameters.siteId was null or undefined when calling getDonationTypes.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/waiting-list/{siteId}/donationType`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters.siteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DonationTypeFromJSON));
    }

    /**
     * By using siteId you get list of predefined donation types
     * Provides the list of donation types associated with the donation site
     */
    async getDonationTypes(requestParameters: GetDonationTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DonationType>> {
        const response = await this.getDonationTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
