/* tslint:disable */
/* eslint-disable */
/**
 * Blood Donors Api
 * Blood donor registration and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xvancoa@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Donor,
} from '../models';
import {
    DonorFromJSON,
    DonorToJSON,
} from '../models';

export interface CreateDonorRequest {
    siteId: string;
    donor: Donor;
}

export interface DeleteDonorRequest {
    siteId: string;
    entryId: string;
}

export interface GetDonorsRequest {
    siteId: string;
}

export interface GetDonorRequest {
    siteId: string;
    entryId: string;
}

export interface UpdateDonorRequest {
    siteId: string;
    entryId: string;
    donor: Donor;
}

/**
 * DonorsApi - interface
 * 
 * @export
 * @interface DonorsApiInterface
 */
export interface DonorsApiInterface {
    /**
     * Use this method to store new entry into the donor list.
     * @summary Saves new entry into waiting list
     * @param {string} siteId pass the id of the particular donation site
     * @param {Donor} donor Waiting list entry to store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApiInterface
     */
    createDonorRaw(requestParameters: CreateDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Donor>>;

    /**
     * Use this method to store new entry into the donor list.
     * Saves new entry into waiting list
     */
    createDonor(requestParameters: CreateDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Donor>;

    /**
     * Use this method to delete the specific entry from the donor list.
     * @summary Deletes specific entry
     * @param {string} siteId pass the id of the particular donation site
     * @param {string} entryId pass the id of the particular entry in the donor list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApiInterface
     */
    deleteDonorRaw(requestParameters: DeleteDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Use this method to delete the specific entry from the donor list.
     * Deletes specific entry
     */
    deleteDonor(requestParameters: DeleteDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * By using siteId you get list of entries in the donor list
     * @summary Provides the donor list
     * @param {string} siteId pass the id of the particular donation site
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApiInterface
     */
    getDonorsRaw(requestParameters: GetDonorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Donor>>>;

    /**
     * By using siteId you get list of entries in the donor list
     * Provides the donor list
     */
    getDonors(requestParameters: GetDonorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Donor>>;

    /**
     * By using siteId and entryId you can details of particular entry item ambulance.
     * @summary Provides details about donor record
     * @param {string} siteId pass the id of the particular donation site
     * @param {string} entryId pass the id of the particular entry in the donor list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApiInterface
     */
    getDonorRaw(requestParameters: GetDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Donor>>;

    /**
     * By using siteId and entryId you can details of particular entry item ambulance.
     * Provides details about donor record
     */
    getDonor(requestParameters: GetDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Donor>;

    /**
     * Use this method to update content of the donor record.
     * @summary Updates specific entry
     * @param {string} siteId pass the id of the particular donation site
     * @param {string} entryId pass the id of the particular entry in the donor list
     * @param {Donor} donor Waiting list entry to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DonorsApiInterface
     */
    updateDonorRaw(requestParameters: UpdateDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Donor>>;

    /**
     * Use this method to update content of the donor record.
     * Updates specific entry
     */
    updateDonor(requestParameters: UpdateDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Donor>;

}

/**
 * 
 */
export class DonorsApi extends runtime.BaseAPI implements DonorsApiInterface {

    /**
     * Use this method to store new entry into the donor list.
     * Saves new entry into waiting list
     */
    async createDonorRaw(requestParameters: CreateDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Donor>> {
        if (requestParameters.siteId === null || requestParameters.siteId === undefined) {
            throw new runtime.RequiredError('siteId','Required parameter requestParameters.siteId was null or undefined when calling createDonor.');
        }

        if (requestParameters.donor === null || requestParameters.donor === undefined) {
            throw new runtime.RequiredError('donor','Required parameter requestParameters.donor was null or undefined when calling createDonor.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/blood-donors/{siteId}/donors`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters.siteId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DonorToJSON(requestParameters.donor),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DonorFromJSON(jsonValue));
    }

    /**
     * Use this method to store new entry into the donor list.
     * Saves new entry into waiting list
     */
    async createDonor(requestParameters: CreateDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Donor> {
        const response = await this.createDonorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to delete the specific entry from the donor list.
     * Deletes specific entry
     */
    async deleteDonorRaw(requestParameters: DeleteDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.siteId === null || requestParameters.siteId === undefined) {
            throw new runtime.RequiredError('siteId','Required parameter requestParameters.siteId was null or undefined when calling deleteDonor.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling deleteDonor.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blood-donors/{siteId}/donors/{entryId}`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters.siteId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Use this method to delete the specific entry from the donor list.
     * Deletes specific entry
     */
    async deleteDonor(requestParameters: DeleteDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDonorRaw(requestParameters, initOverrides);
    }

    /**
     * By using siteId you get list of entries in the donor list
     * Provides the donor list
     */
    async getDonorsRaw(requestParameters: GetDonorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Donor>>> {
        if (requestParameters.siteId === null || requestParameters.siteId === undefined) {
            throw new runtime.RequiredError('siteId','Required parameter requestParameters.siteId was null or undefined when calling getDonors.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blood-donors/{siteId}/donors`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters.siteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DonorFromJSON));
    }

    /**
     * By using siteId you get list of entries in the donor list
     * Provides the donor list
     */
    async getDonors(requestParameters: GetDonorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Donor>> {
        const response = await this.getDonorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * By using siteId and entryId you can details of particular entry item ambulance.
     * Provides details about donor record
     */
    async getDonorRaw(requestParameters: GetDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Donor>> {
        if (requestParameters.siteId === null || requestParameters.siteId === undefined) {
            throw new runtime.RequiredError('siteId','Required parameter requestParameters.siteId was null or undefined when calling getDonor.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling getDonor.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blood-donors/{siteId}/donors/{entryId}`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters.siteId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DonorFromJSON(jsonValue));
    }

    /**
     * By using siteId and entryId you can details of particular entry item ambulance.
     * Provides details about donor record
     */
    async getDonor(requestParameters: GetDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Donor> {
        const response = await this.getDonorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to update content of the donor record.
     * Updates specific entry
     */
    async updateDonorRaw(requestParameters: UpdateDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Donor>> {
        if (requestParameters.siteId === null || requestParameters.siteId === undefined) {
            throw new runtime.RequiredError('siteId','Required parameter requestParameters.siteId was null or undefined when calling updateDonor.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling updateDonor.');
        }

        if (requestParameters.donor === null || requestParameters.donor === undefined) {
            throw new runtime.RequiredError('donor','Required parameter requestParameters.donor was null or undefined when calling updateDonor.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/blood-donors/{siteId}/donors/{entryId}`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters.siteId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DonorToJSON(requestParameters.donor),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DonorFromJSON(jsonValue));
    }

    /**
     * Use this method to update content of the donor record.
     * Updates specific entry
     */
    async updateDonor(requestParameters: UpdateDonorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Donor> {
        const response = await this.updateDonorRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
