/* tslint:disable */
/* eslint-disable */
/**
 * Blood Donors Api
 * Blood donor registration and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vancoa@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DonationType } from './DonationType';
import {
    DonationTypeFromJSON,
    DonationTypeFromJSONTyped,
    DonationTypeToJSON,
} from './DonationType';

/**
 * A single donation in the donor's history (past or upcoming appointment)
 * @export
 * @interface Donation
 */
export interface Donation {
    /**
     * Date and time of the donation appointment
     * @type {Date}
     * @memberof Donation
     */
    date?: Date;
    /**
     *
     * @type {DonationType}
     * @memberof Donation
     */
    donationType?: DonationType;
    /**
     * Status of the donation (e.g. "Rezervácia dokončená", "Dokončené", "Zrušené")
     * @type {string}
     * @memberof Donation
     */
    status?: string;
}

/**
 * Check if a given object implements the Donation interface.
 */
export function instanceOfDonation(value: object): boolean {
    return true;
}

export function DonationFromJSON(json: any): Donation {
    return DonationFromJSONTyped(json, false);
}

export function DonationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Donation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'donationType': !exists(json, 'donationType') ? undefined : DonationTypeFromJSON(json['donationType']),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function DonationToJSON(value?: Donation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'donationType': DonationTypeToJSON(value.donationType),
        'status': value.status,
    };
}
