/* tslint:disable */
/* eslint-disable */
/**
 * Blood Donors Api
 * Blood donor registration and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xvancoa@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Describes disease, symptoms, or other reasons of patient   visit
 * @export
 * @interface DonationType
 */
export interface DonationType {
    /**
     * 
     * @type {string}
     * @memberof DonationType
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof DonationType
     */
    code?: string;
    /**
     * Link to encyclopedical explanation of the patient's donationType
     * @type {string}
     * @memberof DonationType
     */
    reference?: string;
    /**
     * 
     * @type {number}
     * @memberof DonationType
     */
    typicalDurationMinutes?: number;
}

/**
 * Check if a given object implements the DonationType interface.
 */
export function instanceOfDonationType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function DonationTypeFromJSON(json: any): DonationType {
    return DonationTypeFromJSONTyped(json, false);
}

export function DonationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'reference': !exists(json, 'reference') ? undefined : json['reference'],
        'typicalDurationMinutes': !exists(json, 'typicalDurationMinutes') ? undefined : json['typicalDurationMinutes'],
    };
}

export function DonationTypeToJSON(value?: DonationType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'code': value.code,
        'reference': value.reference,
        'typicalDurationMinutes': value.typicalDurationMinutes,
    };
}

