/* tslint:disable */
/* eslint-disable */
/**
 * Blood Donors Api
 * Blood donor registration and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vancoa@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Donation } from './Donation';
import {
    DonationFromJSON,
    DonationFromJSONTyped,
    DonationToJSON,
} from './Donation';

/**
 *
 * @export
 * @interface Donor
 */
export interface Donor {
    /**
     * Unique id of the donor record at this donation site
     * @type {string}
     * @memberof Donor
     */
    id: string;
    /**
     * Full name of the blood donor
     * @type {string}
     * @memberof Donor
     */
    name?: string;
    /**
     * Unique and immutable registration number of the donor. Assigned automatically on registration.
     * @type {string}
     * @memberof Donor
     */
    donorId: string;
    /**
     * Sex of the donor: "M" (muž) or "F" (žena). Relevant for annual donation limits.
     * @type {string}
     * @memberof Donor
     */
    sex?: string;
    /**
     * Blood type of the donor (e.g. A+, 0-, AB+)
     * @type {string}
     * @memberof Donor
     */
    bloodType?: string;
    /**
     * Contact e-mail of the donor
     * @type {string}
     * @memberof Donor
     */
    email?: string;
    /**
     * Contact phone number of the donor
     * @type {string}
     * @memberof Donor
     */
    phone?: string;
    /**
     * Preferred donation type: "blood" (krv), "plasma" (krvná plazma) or "both" (oboje)
     * @type {string}
     * @memberof Donor
     */
    preferredDonationType?: string;
    /**
     * Preferred donation site (id) of the donor
     * @type {string}
     * @memberof Donor
     */
    preferredSite?: string;
    /**
     * Whether the donor is generally eligible to donate (spôsobilý / nespôsobilý)
     * @type {boolean}
     * @memberof Donor
     */
    eligible?: boolean;
    /**
     * General note explaining why the donor is not eligible (e.g. chronic illness). Used when eligible is false.
     * @type {string}
     * @memberof Donor
     */
    eligibilityNote?: string;
    /**
     * Timestamp since when the donor is registered
     * @type {Date}
     * @memberof Donor
     */
    registeredSince: Date;
    /**
     * Reserved appointment time of the next donation. Ignored on post.
     * @type {Date}
     * @memberof Donor
     */
    appointmentStart?: Date;
    /**
     * History of the donor's donations / appointments (termíny)
     * @type {Array<Donation>}
     * @memberof Donor
     */
    donations?: Array<Donation>;
}

/**
 * Check if a given object implements the Donor interface.
 */
export function instanceOfDonor(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "donorId" in value;
    isInstance = isInstance && "registeredSince" in value;

    return isInstance;
}

export function DonorFromJSON(json: any): Donor {
    return DonorFromJSONTyped(json, false);
}

export function DonorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Donor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'donorId': json['donorId'],
        'sex': !exists(json, 'sex') ? undefined : json['sex'],
        'bloodType': !exists(json, 'bloodType') ? undefined : json['bloodType'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'preferredDonationType': !exists(json, 'preferredDonationType') ? undefined : json['preferredDonationType'],
        'preferredSite': !exists(json, 'preferredSite') ? undefined : json['preferredSite'],
        'eligible': !exists(json, 'eligible') ? undefined : json['eligible'],
        'eligibilityNote': !exists(json, 'eligibilityNote') ? undefined : json['eligibilityNote'],
        'registeredSince': (new Date(json['registeredSince'])),
        'appointmentStart': !exists(json, 'appointmentStart') ? undefined : (new Date(json['appointmentStart'])),
        'donations': !exists(json, 'donations') ? undefined : ((json['donations'] as Array<any>).map(DonationFromJSON)),
    };
}

export function DonorToJSON(value?: Donor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'name': value.name,
        'donorId': value.donorId,
        'sex': value.sex,
        'bloodType': value.bloodType,
        'email': value.email,
        'phone': value.phone,
        'preferredDonationType': value.preferredDonationType,
        'preferredSite': value.preferredSite,
        'eligible': value.eligible,
        'eligibilityNote': value.eligibilityNote,
        'registeredSince': (value.registeredSince.toISOString()),
        'appointmentStart': value.appointmentStart === undefined ? undefined : (value.appointmentStart.toISOString()),
        'donations': value.donations === undefined ? undefined : ((value.donations as Array<any>).map(DonationToJSON)),
    };
}
