/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Hlavný aplikačný komponent microfrontendu darcov krvi.
     * Podľa aktuálnej URL (relatívnej k base-path) rozhoduje, či sa zobrazí
     * zoznam darcov alebo editor konkrétneho darcu - funguje ako jednoduchý router.
     */
    interface Cv2xvancoaBloodDonors {
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
        "siteId": string;
    }
    /**
     * Editor darcu - pridanie, úprava a zmazanie (scenáre Darca/C, U, D).
     * Eviduje osobné a kontaktné údaje, pohlavie, krvnú skupinu, preferovaný typ odberu,
     * všeobecnú spôsobilosť na darovanie (pri nespôsobilosti s dôvodom) a zoznam termínov.
     * Registračné číslo darcu sa pri novej registrácii prideľuje automaticky a je nemenné.
     */
    interface Cv2xvancoaBloodDonorsEditor {
        "apiBase": string;
        "entryId": string;
        "siteId": string;
    }
    /**
     * Zoznam registrovaných darcov pre pracovníka transfúznej stanice (scenár Darca/R).
     * Načíta darcov z API; pri každom riadku zobrazuje pohlavie, krvnú skupinu a
     * preferovaný typ odberu. Tlačidlom „+" sa otvára registrácia nového darcu.
     */
    interface Cv2xvancoaBloodDonorsList {
        "apiBase": string;
        "siteId": string;
    }
}
export interface Cv2xvancoaBloodDonorsEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCv2xvancoaBloodDonorsEditorElement;
}
export interface Cv2xvancoaBloodDonorsListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCv2xvancoaBloodDonorsListElement;
}
declare global {
    /**
     * Hlavný aplikačný komponent microfrontendu darcov krvi.
     * Podľa aktuálnej URL (relatívnej k base-path) rozhoduje, či sa zobrazí
     * zoznam darcov alebo editor konkrétneho darcu - funguje ako jednoduchý router.
     */
    interface HTMLCv2xvancoaBloodDonorsElement extends Components.Cv2xvancoaBloodDonors, HTMLStencilElement {
    }
    var HTMLCv2xvancoaBloodDonorsElement: {
        prototype: HTMLCv2xvancoaBloodDonorsElement;
        new (): HTMLCv2xvancoaBloodDonorsElement;
    };
    interface HTMLCv2xvancoaBloodDonorsEditorElementEventMap {
        "editor-closed": string;
    }
    /**
     * Editor darcu - pridanie, úprava a zmazanie (scenáre Darca/C, U, D).
     * Eviduje osobné a kontaktné údaje, pohlavie, krvnú skupinu, preferovaný typ odberu,
     * všeobecnú spôsobilosť na darovanie (pri nespôsobilosti s dôvodom) a zoznam termínov.
     * Registračné číslo darcu sa pri novej registrácii prideľuje automaticky a je nemenné.
     */
    interface HTMLCv2xvancoaBloodDonorsEditorElement extends Components.Cv2xvancoaBloodDonorsEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsEditorElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsEditorElement, ev: Cv2xvancoaBloodDonorsEditorCustomEvent<HTMLCv2xvancoaBloodDonorsEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsEditorElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsEditorElement, ev: Cv2xvancoaBloodDonorsEditorCustomEvent<HTMLCv2xvancoaBloodDonorsEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCv2xvancoaBloodDonorsEditorElement: {
        prototype: HTMLCv2xvancoaBloodDonorsEditorElement;
        new (): HTMLCv2xvancoaBloodDonorsEditorElement;
    };
    interface HTMLCv2xvancoaBloodDonorsListElementEventMap {
        "entry-clicked": string;
    }
    /**
     * Zoznam registrovaných darcov pre pracovníka transfúznej stanice (scenár Darca/R).
     * Načíta darcov z API; pri každom riadku zobrazuje pohlavie, krvnú skupinu a
     * preferovaný typ odberu. Tlačidlom „+" sa otvára registrácia nového darcu.
     */
    interface HTMLCv2xvancoaBloodDonorsListElement extends Components.Cv2xvancoaBloodDonorsList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsListElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsListElement, ev: Cv2xvancoaBloodDonorsListCustomEvent<HTMLCv2xvancoaBloodDonorsListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsListElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsListElement, ev: Cv2xvancoaBloodDonorsListCustomEvent<HTMLCv2xvancoaBloodDonorsListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCv2xvancoaBloodDonorsListElement: {
        prototype: HTMLCv2xvancoaBloodDonorsListElement;
        new (): HTMLCv2xvancoaBloodDonorsListElement;
    };
    interface HTMLElementTagNameMap {
        "cv2xvancoa-blood-donors": HTMLCv2xvancoaBloodDonorsElement;
        "cv2xvancoa-blood-donors-editor": HTMLCv2xvancoaBloodDonorsEditorElement;
        "cv2xvancoa-blood-donors-list": HTMLCv2xvancoaBloodDonorsListElement;
    }
}
declare namespace LocalJSX {
    /**
     * Hlavný aplikačný komponent microfrontendu darcov krvi.
     * Podľa aktuálnej URL (relatívnej k base-path) rozhoduje, či sa zobrazí
     * zoznam darcov alebo editor konkrétneho darcu - funguje ako jednoduchý router.
     */
    interface Cv2xvancoaBloodDonors {
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
        "siteId"?: string;
    }
    /**
     * Editor darcu - pridanie, úprava a zmazanie (scenáre Darca/C, U, D).
     * Eviduje osobné a kontaktné údaje, pohlavie, krvnú skupinu, preferovaný typ odberu,
     * všeobecnú spôsobilosť na darovanie (pri nespôsobilosti s dôvodom) a zoznam termínov.
     * Registračné číslo darcu sa pri novej registrácii prideľuje automaticky a je nemenné.
     */
    interface Cv2xvancoaBloodDonorsEditor {
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: Cv2xvancoaBloodDonorsEditorCustomEvent<string>) => void;
        "siteId"?: string;
    }
    /**
     * Zoznam registrovaných darcov pre pracovníka transfúznej stanice (scenár Darca/R).
     * Načíta darcov z API; pri každom riadku zobrazuje pohlavie, krvnú skupinu a
     * preferovaný typ odberu. Tlačidlom „+" sa otvára registrácia nového darcu.
     */
    interface Cv2xvancoaBloodDonorsList {
        "apiBase"?: string;
        "onEntry-clicked"?: (event: Cv2xvancoaBloodDonorsListCustomEvent<string>) => void;
        "siteId"?: string;
    }

    interface Cv2xvancoaBloodDonorsAttributes {
        "basePath": string;
        "apiBase": string;
        "siteId": string;
    }
    interface Cv2xvancoaBloodDonorsEditorAttributes {
        "entryId": string;
        "siteId": string;
        "apiBase": string;
    }
    interface Cv2xvancoaBloodDonorsListAttributes {
        "apiBase": string;
        "siteId": string;
    }

    interface IntrinsicElements {
        "cv2xvancoa-blood-donors": Omit<Cv2xvancoaBloodDonors, keyof Cv2xvancoaBloodDonorsAttributes> & { [K in keyof Cv2xvancoaBloodDonors & keyof Cv2xvancoaBloodDonorsAttributes]?: Cv2xvancoaBloodDonors[K] } & { [K in keyof Cv2xvancoaBloodDonors & keyof Cv2xvancoaBloodDonorsAttributes as `attr:${K}`]?: Cv2xvancoaBloodDonorsAttributes[K] } & { [K in keyof Cv2xvancoaBloodDonors & keyof Cv2xvancoaBloodDonorsAttributes as `prop:${K}`]?: Cv2xvancoaBloodDonors[K] };
        "cv2xvancoa-blood-donors-editor": Omit<Cv2xvancoaBloodDonorsEditor, keyof Cv2xvancoaBloodDonorsEditorAttributes> & { [K in keyof Cv2xvancoaBloodDonorsEditor & keyof Cv2xvancoaBloodDonorsEditorAttributes]?: Cv2xvancoaBloodDonorsEditor[K] } & { [K in keyof Cv2xvancoaBloodDonorsEditor & keyof Cv2xvancoaBloodDonorsEditorAttributes as `attr:${K}`]?: Cv2xvancoaBloodDonorsEditorAttributes[K] } & { [K in keyof Cv2xvancoaBloodDonorsEditor & keyof Cv2xvancoaBloodDonorsEditorAttributes as `prop:${K}`]?: Cv2xvancoaBloodDonorsEditor[K] };
        "cv2xvancoa-blood-donors-list": Omit<Cv2xvancoaBloodDonorsList, keyof Cv2xvancoaBloodDonorsListAttributes> & { [K in keyof Cv2xvancoaBloodDonorsList & keyof Cv2xvancoaBloodDonorsListAttributes]?: Cv2xvancoaBloodDonorsList[K] } & { [K in keyof Cv2xvancoaBloodDonorsList & keyof Cv2xvancoaBloodDonorsListAttributes as `attr:${K}`]?: Cv2xvancoaBloodDonorsListAttributes[K] } & { [K in keyof Cv2xvancoaBloodDonorsList & keyof Cv2xvancoaBloodDonorsListAttributes as `prop:${K}`]?: Cv2xvancoaBloodDonorsList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Hlavný aplikačný komponent microfrontendu darcov krvi.
             * Podľa aktuálnej URL (relatívnej k base-path) rozhoduje, či sa zobrazí
             * zoznam darcov alebo editor konkrétneho darcu - funguje ako jednoduchý router.
             */
            "cv2xvancoa-blood-donors": LocalJSX.IntrinsicElements["cv2xvancoa-blood-donors"] & JSXBase.HTMLAttributes<HTMLCv2xvancoaBloodDonorsElement>;
            /**
             * Editor darcu - pridanie, úprava a zmazanie (scenáre Darca/C, U, D).
             * Eviduje osobné a kontaktné údaje, pohlavie, krvnú skupinu, preferovaný typ odberu,
             * všeobecnú spôsobilosť na darovanie (pri nespôsobilosti s dôvodom) a zoznam termínov.
             * Registračné číslo darcu sa pri novej registrácii prideľuje automaticky a je nemenné.
             */
            "cv2xvancoa-blood-donors-editor": LocalJSX.IntrinsicElements["cv2xvancoa-blood-donors-editor"] & JSXBase.HTMLAttributes<HTMLCv2xvancoaBloodDonorsEditorElement>;
            /**
             * Zoznam registrovaných darcov pre pracovníka transfúznej stanice (scenár Darca/R).
             * Načíta darcov z API; pri každom riadku zobrazuje pohlavie, krvnú skupinu a
             * preferovaný typ odberu. Tlačidlom „+" sa otvára registrácia nového darcu.
             */
            "cv2xvancoa-blood-donors-list": LocalJSX.IntrinsicElements["cv2xvancoa-blood-donors-list"] & JSXBase.HTMLAttributes<HTMLCv2xvancoaBloodDonorsListElement>;
        }
    }
}
