/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Donation } from "./api/blood-donors";
export { Donation } from "./api/blood-donors";
export namespace Components {
    /**
     * Hlavný aplikačný komponent microfrontendu darcov krvi.
     * Podľa aktuálnej URL (relatívnej k base-path) rozhoduje, ktorá obrazovka sa
     * zobrazí - funguje ako jednoduchý router.
     * Flow sa delí podľa role prihláseného používateľa (OIDC/Dex cez Envoy Gateway):
     *  - pracovník (pracovnik): zoznam darcov, plný editor ľubovoľného darcu, rezervácia
     *  - darca (darca): iba rezervácia a vlastný účet/profil (self-edit), bez zoznamu darcov
     */
    interface Cv2xvancoaBloodDonors {
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath": string;
        "role"?: string;
        "siteId"?: string;
    }
    interface Cv2xvancoaBloodDonorsCalendar {
        "apiBase"?: string;
        "donations"?: Donation[];
        /**
          * @default true
         */
        "donorEligible"?: boolean;
        "donorId"?: string;
        /**
          * @default false
         */
        "pickerMode"?: boolean;
        "preselectType"?: string;
        "sex"?: string;
        "siteId"?: string;
        "userEmail"?: string;
    }
    interface Cv2xvancoaBloodDonorsEditor {
        "apiBase"?: string;
        "entryId"?: string;
        /**
          * @default "worker"
         */
        "mode": string;
        "siteId"?: string;
    }
    /**
     * Zoznam registrovaných darcov pre pracovníka transfúznej stanice (scenár Darca/R).
     * Načíta darcov z API; pri každom riadku zobrazuje pohlavie, krvnú skupinu a
     * preferovaný typ odberu. Tlačidlom „+" sa otvára registrácia nového darcu.
     */
    interface Cv2xvancoaBloodDonorsList {
        "apiBase"?: string;
        "siteId"?: string;
    }
    /**
     * Obrazovka "Môj účet" - vlastný pohľad darcu (scenár Darca/CRUD: prezeranie profilu a histórie).
     * Bez prihlásenia je naviazaná na konkrétneho darcu (donorId), inak na prvého v zozname.
     */
    interface Cv2xvancoaBloodDonorsProfile {
        "apiBase"?: string;
        "donorId"?: string;
        "role"?: string;
        "siteId"?: string;
        "userEmail"?: string;
        "userName"?: string;
    }
}
export interface Cv2xvancoaBloodDonorsCalendarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCv2xvancoaBloodDonorsCalendarElement;
}
export interface Cv2xvancoaBloodDonorsEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCv2xvancoaBloodDonorsEditorElement;
}
export interface Cv2xvancoaBloodDonorsListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCv2xvancoaBloodDonorsListElement;
}
export interface Cv2xvancoaBloodDonorsProfileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCv2xvancoaBloodDonorsProfileElement;
}
declare global {
    /**
     * Hlavný aplikačný komponent microfrontendu darcov krvi.
     * Podľa aktuálnej URL (relatívnej k base-path) rozhoduje, ktorá obrazovka sa
     * zobrazí - funguje ako jednoduchý router.
     * Flow sa delí podľa role prihláseného používateľa (OIDC/Dex cez Envoy Gateway):
     *  - pracovník (pracovnik): zoznam darcov, plný editor ľubovoľného darcu, rezervácia
     *  - darca (darca): iba rezervácia a vlastný účet/profil (self-edit), bez zoznamu darcov
     */
    interface HTMLCv2xvancoaBloodDonorsElement extends Components.Cv2xvancoaBloodDonors, HTMLStencilElement {
    }
    var HTMLCv2xvancoaBloodDonorsElement: {
        prototype: HTMLCv2xvancoaBloodDonorsElement;
        new (): HTMLCv2xvancoaBloodDonorsElement;
    };
    interface HTMLCv2xvancoaBloodDonorsCalendarElementEventMap {
        "slot-selected": { date: Date; time: string; type: string };
    }
    interface HTMLCv2xvancoaBloodDonorsCalendarElement extends Components.Cv2xvancoaBloodDonorsCalendar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsCalendarElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsCalendarElement, ev: Cv2xvancoaBloodDonorsCalendarCustomEvent<HTMLCv2xvancoaBloodDonorsCalendarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsCalendarElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsCalendarElement, ev: Cv2xvancoaBloodDonorsCalendarCustomEvent<HTMLCv2xvancoaBloodDonorsCalendarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCv2xvancoaBloodDonorsCalendarElement: {
        prototype: HTMLCv2xvancoaBloodDonorsCalendarElement;
        new (): HTMLCv2xvancoaBloodDonorsCalendarElement;
    };
    interface HTMLCv2xvancoaBloodDonorsEditorElementEventMap {
        "editor-closed": string;
        "notify": string;
    }
    interface HTMLCv2xvancoaBloodDonorsEditorElement extends Components.Cv2xvancoaBloodDonorsEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsEditorElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsEditorElement, ev: Cv2xvancoaBloodDonorsEditorCustomEvent<HTMLCv2xvancoaBloodDonorsEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsEditorElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsEditorElement, ev: Cv2xvancoaBloodDonorsEditorCustomEvent<HTMLCv2xvancoaBloodDonorsEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCv2xvancoaBloodDonorsEditorElement: {
        prototype: HTMLCv2xvancoaBloodDonorsEditorElement;
        new (): HTMLCv2xvancoaBloodDonorsEditorElement;
    };
    interface HTMLCv2xvancoaBloodDonorsListElementEventMap {
        "entry-clicked": string;
        "notify": string;
    }
    /**
     * Zoznam registrovaných darcov pre pracovníka transfúznej stanice (scenár Darca/R).
     * Načíta darcov z API; pri každom riadku zobrazuje pohlavie, krvnú skupinu a
     * preferovaný typ odberu. Tlačidlom „+" sa otvára registrácia nového darcu.
     */
    interface HTMLCv2xvancoaBloodDonorsListElement extends Components.Cv2xvancoaBloodDonorsList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsListElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsListElement, ev: Cv2xvancoaBloodDonorsListCustomEvent<HTMLCv2xvancoaBloodDonorsListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsListElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsListElement, ev: Cv2xvancoaBloodDonorsListCustomEvent<HTMLCv2xvancoaBloodDonorsListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCv2xvancoaBloodDonorsListElement: {
        prototype: HTMLCv2xvancoaBloodDonorsListElement;
        new (): HTMLCv2xvancoaBloodDonorsListElement;
    };
    interface HTMLCv2xvancoaBloodDonorsProfileElementEventMap {
        "edit-profile": string;
    }
    /**
     * Obrazovka "Môj účet" - vlastný pohľad darcu (scenár Darca/CRUD: prezeranie profilu a histórie).
     * Bez prihlásenia je naviazaná na konkrétneho darcu (donorId), inak na prvého v zozname.
     */
    interface HTMLCv2xvancoaBloodDonorsProfileElement extends Components.Cv2xvancoaBloodDonorsProfile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsProfileElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsProfileElement, ev: Cv2xvancoaBloodDonorsProfileCustomEvent<HTMLCv2xvancoaBloodDonorsProfileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCv2xvancoaBloodDonorsProfileElementEventMap>(type: K, listener: (this: HTMLCv2xvancoaBloodDonorsProfileElement, ev: Cv2xvancoaBloodDonorsProfileCustomEvent<HTMLCv2xvancoaBloodDonorsProfileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCv2xvancoaBloodDonorsProfileElement: {
        prototype: HTMLCv2xvancoaBloodDonorsProfileElement;
        new (): HTMLCv2xvancoaBloodDonorsProfileElement;
    };
    interface HTMLElementTagNameMap {
        "cv2xvancoa-blood-donors": HTMLCv2xvancoaBloodDonorsElement;
        "cv2xvancoa-blood-donors-calendar": HTMLCv2xvancoaBloodDonorsCalendarElement;
        "cv2xvancoa-blood-donors-editor": HTMLCv2xvancoaBloodDonorsEditorElement;
        "cv2xvancoa-blood-donors-list": HTMLCv2xvancoaBloodDonorsListElement;
        "cv2xvancoa-blood-donors-profile": HTMLCv2xvancoaBloodDonorsProfileElement;
    }
}
declare namespace LocalJSX {
    /**
     * Hlavný aplikačný komponent microfrontendu darcov krvi.
     * Podľa aktuálnej URL (relatívnej k base-path) rozhoduje, ktorá obrazovka sa
     * zobrazí - funguje ako jednoduchý router.
     * Flow sa delí podľa role prihláseného používateľa (OIDC/Dex cez Envoy Gateway):
     *  - pracovník (pracovnik): zoznam darcov, plný editor ľubovoľného darcu, rezervácia
     *  - darca (darca): iba rezervácia a vlastný účet/profil (self-edit), bez zoznamu darcov
     */
    interface Cv2xvancoaBloodDonors {
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
        "role"?: string;
        "siteId"?: string;
    }
    interface Cv2xvancoaBloodDonorsCalendar {
        "apiBase"?: string;
        "donations"?: Donation[];
        /**
          * @default true
         */
        "donorEligible"?: boolean;
        "donorId"?: string;
        "onSlot-selected"?: (event: Cv2xvancoaBloodDonorsCalendarCustomEvent<{ date: Date; time: string; type: string }>) => void;
        /**
          * @default false
         */
        "pickerMode"?: boolean;
        "preselectType"?: string;
        "sex"?: string;
        "siteId"?: string;
        "userEmail"?: string;
    }
    interface Cv2xvancoaBloodDonorsEditor {
        "apiBase"?: string;
        "entryId"?: string;
        /**
          * @default "worker"
         */
        "mode"?: string;
        "onEditor-closed"?: (event: Cv2xvancoaBloodDonorsEditorCustomEvent<string>) => void;
        "onNotify"?: (event: Cv2xvancoaBloodDonorsEditorCustomEvent<string>) => void;
        "siteId"?: string;
    }
    /**
     * Zoznam registrovaných darcov pre pracovníka transfúznej stanice (scenár Darca/R).
     * Načíta darcov z API; pri každom riadku zobrazuje pohlavie, krvnú skupinu a
     * preferovaný typ odberu. Tlačidlom „+" sa otvára registrácia nového darcu.
     */
    interface Cv2xvancoaBloodDonorsList {
        "apiBase"?: string;
        "onEntry-clicked"?: (event: Cv2xvancoaBloodDonorsListCustomEvent<string>) => void;
        "onNotify"?: (event: Cv2xvancoaBloodDonorsListCustomEvent<string>) => void;
        "siteId"?: string;
    }
    /**
     * Obrazovka "Môj účet" - vlastný pohľad darcu (scenár Darca/CRUD: prezeranie profilu a histórie).
     * Bez prihlásenia je naviazaná na konkrétneho darcu (donorId), inak na prvého v zozname.
     */
    interface Cv2xvancoaBloodDonorsProfile {
        "apiBase"?: string;
        "donorId"?: string;
        "onEdit-profile"?: (event: Cv2xvancoaBloodDonorsProfileCustomEvent<string>) => void;
        "role"?: string;
        "siteId"?: string;
        "userEmail"?: string;
        "userName"?: string;
    }

    interface Cv2xvancoaBloodDonorsAttributes {
        "basePath": string;
        "apiBase": string;
        "siteId": string;
        "role": string;
    }
    interface Cv2xvancoaBloodDonorsCalendarAttributes {
        "apiBase": string;
        "siteId": string;
        "donorId": string;
        "userEmail": string;
        "pickerMode": boolean;
        "sex": string;
        "donorEligible": boolean;
        "preselectType": string;
    }
    interface Cv2xvancoaBloodDonorsEditorAttributes {
        "entryId": string;
        "siteId": string;
        "apiBase": string;
        "mode": string;
    }
    interface Cv2xvancoaBloodDonorsListAttributes {
        "apiBase": string;
        "siteId": string;
    }
    interface Cv2xvancoaBloodDonorsProfileAttributes {
        "apiBase": string;
        "siteId": string;
        "donorId": string;
        "userEmail": string;
        "userName": string;
        "role": string;
    }

    interface IntrinsicElements {
        "cv2xvancoa-blood-donors": Omit<Cv2xvancoaBloodDonors, keyof Cv2xvancoaBloodDonorsAttributes> & { [K in keyof Cv2xvancoaBloodDonors & keyof Cv2xvancoaBloodDonorsAttributes]?: Cv2xvancoaBloodDonors[K] } & { [K in keyof Cv2xvancoaBloodDonors & keyof Cv2xvancoaBloodDonorsAttributes as `attr:${K}`]?: Cv2xvancoaBloodDonorsAttributes[K] } & { [K in keyof Cv2xvancoaBloodDonors & keyof Cv2xvancoaBloodDonorsAttributes as `prop:${K}`]?: Cv2xvancoaBloodDonors[K] };
        "cv2xvancoa-blood-donors-calendar": Omit<Cv2xvancoaBloodDonorsCalendar, keyof Cv2xvancoaBloodDonorsCalendarAttributes> & { [K in keyof Cv2xvancoaBloodDonorsCalendar & keyof Cv2xvancoaBloodDonorsCalendarAttributes]?: Cv2xvancoaBloodDonorsCalendar[K] } & { [K in keyof Cv2xvancoaBloodDonorsCalendar & keyof Cv2xvancoaBloodDonorsCalendarAttributes as `attr:${K}`]?: Cv2xvancoaBloodDonorsCalendarAttributes[K] } & { [K in keyof Cv2xvancoaBloodDonorsCalendar & keyof Cv2xvancoaBloodDonorsCalendarAttributes as `prop:${K}`]?: Cv2xvancoaBloodDonorsCalendar[K] };
        "cv2xvancoa-blood-donors-editor": Omit<Cv2xvancoaBloodDonorsEditor, keyof Cv2xvancoaBloodDonorsEditorAttributes> & { [K in keyof Cv2xvancoaBloodDonorsEditor & keyof Cv2xvancoaBloodDonorsEditorAttributes]?: Cv2xvancoaBloodDonorsEditor[K] } & { [K in keyof Cv2xvancoaBloodDonorsEditor & keyof Cv2xvancoaBloodDonorsEditorAttributes as `attr:${K}`]?: Cv2xvancoaBloodDonorsEditorAttributes[K] } & { [K in keyof Cv2xvancoaBloodDonorsEditor & keyof Cv2xvancoaBloodDonorsEditorAttributes as `prop:${K}`]?: Cv2xvancoaBloodDonorsEditor[K] };
        "cv2xvancoa-blood-donors-list": Omit<Cv2xvancoaBloodDonorsList, keyof Cv2xvancoaBloodDonorsListAttributes> & { [K in keyof Cv2xvancoaBloodDonorsList & keyof Cv2xvancoaBloodDonorsListAttributes]?: Cv2xvancoaBloodDonorsList[K] } & { [K in keyof Cv2xvancoaBloodDonorsList & keyof Cv2xvancoaBloodDonorsListAttributes as `attr:${K}`]?: Cv2xvancoaBloodDonorsListAttributes[K] } & { [K in keyof Cv2xvancoaBloodDonorsList & keyof Cv2xvancoaBloodDonorsListAttributes as `prop:${K}`]?: Cv2xvancoaBloodDonorsList[K] };
        "cv2xvancoa-blood-donors-profile": Omit<Cv2xvancoaBloodDonorsProfile, keyof Cv2xvancoaBloodDonorsProfileAttributes> & { [K in keyof Cv2xvancoaBloodDonorsProfile & keyof Cv2xvancoaBloodDonorsProfileAttributes]?: Cv2xvancoaBloodDonorsProfile[K] } & { [K in keyof Cv2xvancoaBloodDonorsProfile & keyof Cv2xvancoaBloodDonorsProfileAttributes as `attr:${K}`]?: Cv2xvancoaBloodDonorsProfileAttributes[K] } & { [K in keyof Cv2xvancoaBloodDonorsProfile & keyof Cv2xvancoaBloodDonorsProfileAttributes as `prop:${K}`]?: Cv2xvancoaBloodDonorsProfile[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Hlavný aplikačný komponent microfrontendu darcov krvi.
             * Podľa aktuálnej URL (relatívnej k base-path) rozhoduje, ktorá obrazovka sa
             * zobrazí - funguje ako jednoduchý router.
             * Flow sa delí podľa role prihláseného používateľa (OIDC/Dex cez Envoy Gateway):
             *  - pracovník (pracovnik): zoznam darcov, plný editor ľubovoľného darcu, rezervácia
             *  - darca (darca): iba rezervácia a vlastný účet/profil (self-edit), bez zoznamu darcov
             */
            "cv2xvancoa-blood-donors": LocalJSX.IntrinsicElements["cv2xvancoa-blood-donors"] & JSXBase.HTMLAttributes<HTMLCv2xvancoaBloodDonorsElement>;
            "cv2xvancoa-blood-donors-calendar": LocalJSX.IntrinsicElements["cv2xvancoa-blood-donors-calendar"] & JSXBase.HTMLAttributes<HTMLCv2xvancoaBloodDonorsCalendarElement>;
            "cv2xvancoa-blood-donors-editor": LocalJSX.IntrinsicElements["cv2xvancoa-blood-donors-editor"] & JSXBase.HTMLAttributes<HTMLCv2xvancoaBloodDonorsEditorElement>;
            /**
             * Zoznam registrovaných darcov pre pracovníka transfúznej stanice (scenár Darca/R).
             * Načíta darcov z API; pri každom riadku zobrazuje pohlavie, krvnú skupinu a
             * preferovaný typ odberu. Tlačidlom „+" sa otvára registrácia nového darcu.
             */
            "cv2xvancoa-blood-donors-list": LocalJSX.IntrinsicElements["cv2xvancoa-blood-donors-list"] & JSXBase.HTMLAttributes<HTMLCv2xvancoaBloodDonorsListElement>;
            /**
             * Obrazovka "Môj účet" - vlastný pohľad darcu (scenár Darca/CRUD: prezeranie profilu a histórie).
             * Bez prihlásenia je naviazaná na konkrétneho darcu (donorId), inak na prvého v zozname.
             */
            "cv2xvancoa-blood-donors-profile": LocalJSX.IntrinsicElements["cv2xvancoa-blood-donors-profile"] & JSXBase.HTMLAttributes<HTMLCv2xvancoaBloodDonorsProfileElement>;
        }
    }
}
